server: 
  port: 9007
spring: 
  application:  
    name: tensquare-seearch #指定服务名
  data:
    elasticsearch:
      cluster-nodes: 192.168.37.137:9300
      cluster-name : docker-cluster
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:6868/eureka'
  instance:
    prefer-ip-address: true


