server: 
  port: 9008
spring:
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.37.137:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.37.137
  redis:
    host: 192.168.37.137
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:6868/eureka'
  instance:
    prefer-ip-address: true


jwt:
  config:
    key: itcast
    ttl: 360000 #持续时间
